# Generated by Django 2.1 on 2018-08-15 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('price', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=500)),
                ('sellerName', models.CharField(max_length=50)),
                ('sellerAddress', models.CharField(max_length=100)),
                ('sellerPhoneNumber', models.IntegerField(max_length=13)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shopdata.Categories')),
            ],
        ),
    ]
