# Generated by Django 2.1 on 2018-08-15 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shopdata', '0003_auto_20180815_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='name',
            new_name='categoryName',
        ),
    ]
